# Generated by Django 5.1.7 on 2025-04-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0012_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('unit_id', models.CharField(max_length=50)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sparc.profile')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sparc.sale')),
            ],
        ),
    ]
