# Generated by Django 5.1.7 on 2025-04-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0014_delete_commission'),
    ]

    operations = [
    ]
