# Generated by Django 5.1.7 on 2025-04-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0015_add_commission_structures'),
    ]

    operations = [
    ]
