# Generated by Django 5.1.7 on 2025-04-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0016_add_commission_structures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
